baseurl: https://ghl-ball.github.io/resolving-baseball/
languageCode: ja
title: Resolving Baseball Blog
theme: hugo-theme-stack

params:
  mainSections:
    - analysis
    - breakdown
  featuredImageField: image
  rssFullContent: false
  favicon: /statics/images/favicon.png
  
  footer:
    since: 2025
    customText: トレバ-(^o^)丿
    
  dateFormat:
    published: 2006年1月2日
    lastUpdated: 2006年1月2日 15時4分
    
  sidebar:
    subtitle: Aspiring Saberistの備忘録
    avatar:
      enabled: false
      
  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: false
      
  comments:
    enabled: true
    provider: disqus
    disqus:
      shortname: "trevor-4"
    
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 10
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: breakdown
      name: 解説系
      url: /breakdown/
      weight: 3
    - identifier: analysis
      name: 分析系
      url: /analysis/
      weight: 4
    - identifier: memo
      name: メモ
      url: /memo/
      weight: 5

  social:
    - identifier: twitter
      name: Twitter
      url: https://x.com/GHiLiBall
      weight: 10
      params:
        icon: brand-twitter 
    - identifier: note
      name: note
      url: https://note.com/calm_phlox375
      weight: 20
      params:
        icon: archives
    - identifier: github
      name: GitHub
      url: https://github.com/ghl-ball
      weight: 30
      params:
        icon: brand-github
    - identifier: gmail
      name: Gmail
      url: mailto:trevormetrics@gmail.com
      weight: 40
      params:
        icon: messages
        
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4