baseurl: /resolving-baseball/
languageCode: ja
title: Resolving Baseball
theme: hugo-lithium
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: 解説系
      url: /breakdown/
      weight: 3
    - name: 分析系
      url: /analysis/
      weight: 4
    - name: メモ
      url: /memo/
      weight: 5
    - name: note
      url: https://note.com/calm_phlox375
      weight: 6
    - name: Twitter
      url: https://x.com/GHiLiBall
      weight: 7
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: 野球の分析サイト
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - python
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
logo:
  url: /logo.png    
  alt: Logo
  height: 50
  width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false